import { Serie } from './serie.js';
export var series = [
    new Serie(1, "Breaking Bad", "AMC", 5, "Set and filmed in Albuquerque, New Mexico, the series tells the story of Walter White, a struggling and depressed high school chemistry teacher who is diagnosed with lung cancer.", "https://www.amc.com/shows/breaking-bad", "https://i.blogs.es/6d84c8/breaking-bad/1366_2000.jpg"),
    new Serie(2, "Orange Is the New Black", "Netflix", 6, "The series begins revolving around Piper Chapman, a woman in her thirties living in New York City who is sentenced to 15 months in Litchfield Penitentiary.", "https://www.netflix.com/co/title/70242311", "https://www.pride.com/media-library/image.jpg?id=31077833&width=980"),
    new Serie(3, "Game of Thrones", "HBO", 7, "Nine noble families wage war against each other in order to gain control over the mythical land of Westeros. Meanwhile, a force is rising after millenniums.", "https://www.hbo.com/game-of-thrones", "https://www.eltiempo.com/files/image_1200_680/uploads/2022/07/19/62d6c68bda149.png"),
    new Serie(4, "The Big Bang Theory", "CBS", 12, "Leonard and Sheldon are brilliant physicists—geniuses in the laboratory but socially challenged everywhere else. Enter beautiful, street-smart neighbor Penny.", "https://www.cbs.com/shows/big_bang_theory/about/", "https://assetscdn1.paytm.com/images/catalog/product/H/HO/HOMBIG-BANG-THEHK-P630247D60B33F4/1563111551192_0..jpg"),
    new Serie(5, "Sherlock", "BBC", 4, "Sherlock depicts consulting detective Sherlock Holmes (Benedict Cumberbatch) solving various mysteries in modern-day London. Holmes is assisted by his flatmate and friend.", "https://www.bbc.co.uk/programmes/b018ttws", "https://wehaveartsdegrees.files.wordpress.com/2014/01/title.jpg"),
    new Serie(6, "A Very English Scandal", "BBC", 2, "A Very English Scandal is a fact-based three-part British television comedy-drama miniseries based on John Preston's book of the same name.", "https://www.bbc.co.uk/programmes/p065smy4", "https://i.ytimg.com/vi/pj8MTWVrl9s/maxresdefault.jpg"),
];
